FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY ./src/frontend /app/src
COPY ./src/frontend/requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8081

CMD ["python", "-m", "src.ui.ui_app"]